# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

WORKLOAD_NAME: "game-analytics-pipeline"

INGEST_MODE: "KINESIS_DATA_STREAMS"
REAL_TIME_ANALYTICS: false
DATA_STACK: "DATA_LAKE"
ENABLE_APACHE_ICEBERG_SUPPORT: true

EVENTS_DATABASE: "game_analytics"
RAW_EVENTS_TABLE: "raw_events"
RAW_EVENTS_PREFIX: "raw_events"
PROCESSED_EVENTS_PREFIX: "processed_events"
GLUE_TMP_PREFIX: "glueetl-tmp"

STREAM_PROVISIONED: false
STREAM_SHARD_COUNT: 1

API_STAGE_NAME: "prod"
DEV_MODE: true
S3_BACKUP_MODE: false

EMAIL_ADDRESS: "analyticsprod@dinopoloclub.com"
CLOUDWATCH_RETENTION_DAYS: 30

CDK_VERSION: "2.169.0"
NODE_VERSION: "latest"
PYTHON_VERSION: "3.8"